[build]
  base    = "."
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "https://fluffysamurai.netlify.com/*"
  to = "https://fluffysamurai.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://fluffysamurai.netlify.com/*"
  to = "http://fluffysamurai.io/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"
