name: CI Pipeline
on: [push]

jobs:
  prettier_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm ci
      - name: prettier check
        run: npm run prettier:check
